/* eslint-disable react/jsx-no-comment-textnodes */
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kanban Board</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col font-inter">
        <div className="mx-10 my-10">
          <h1 className="font-bold text-3xl">Kanban Board</h1>
          <p className="text-gray-600 text-sm">A board to track your progress.</p>
        </div>
        <div className="flex flex-row bg-slate-50 mx-8 rounded-md">
          <div className="flex-col mx-2 my-2 flex-auto">
            <button disabled className="rounded-full bg-slate-200">
              <h1 className="px-2 py-1 font-semibold text-gray-700">Last week</h1>
            </button>
            {/* card code*/}
            <div className="bg-white mx-2 my-2 rounded-md shadow-md"> 
              <h1 className="font-semibold px-2 py-2 text-base">Review scope</h1> 
              <p className="text-gray-600 px-2">Description</p>
              <button disabled className="rounded-sm bg-red-300 mx-2 my-2">
                <p className="px-2 font-semibold text-gray-800">Due 4/11</p>
              </button>
            </div>

            <div> item 2 </div>
          </div>
          <div className="flex-col flex-auto">
            <h1>This Week</h1>
            <div> item 1 </div>
            <div> item 2 </div>
          </div>
          <div className="flex-col flex-auto">
            <h1>Next Week</h1>
            <div> item 1 </div>
            <div> item 2 </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
